== NAME ==

MITHGrid.Data.initPager

== SYNOPSIS ==

--------------------------------------------------------------------------------------------
page = MITHGrid.Data.initPager({ options list... });
--------------------------------------------------------------------------------------------

== DESCRIPTION ==

Data pagers allow paging through a set of items based on the value of an expression.

== EVENTS ==

== METHODS ==

=== Constructor ===
--------------------------------------------------------------------------------------------
view = MITHGrid.Data.initPager({ options list... });
--------------------------------------------------------------------------------------------

The constructor has the following options:

dataStore::
  The data store or data view holding the items the pager pages through. A data view can be used to
restrict the set of items the pager is paging through based on properties of the items that are not
dependent on a mutable range. 
+
For example, to page through the pages in a book, you can use a data view selecting items of type +Page+
as the +dataStore+ for a pager that uses the expression +'.page'+ to allow selection of a range of +Page+
items based on the items' +page+ property.

expressions::
  An array of graph traversal expressions used to calculate the key for each item. This key is used to
sort the list of items that the pager is paging over.

=== Range Selection ===

setKeyRange(left, right)::
  Selects items whose keys fall in the range (left, right) inclusive.
+
To select items with only a particular value, call +setKeyRange+ with equal bounds.

== SEE ALSO ==

Data.View